atecnica_show:
    pattern:  /{id}/show
    defaults: { _controller: "AtBundle:Atecnica:show" }

atecnica_ver_historico:
    pattern:  /{id}/ver_historico
    defaults: { _controller: "AtBundle:Atecnica:verHistorico" }

atecnica_buscador:
    pattern:  /buscador
    defaults: { _controller: "AtBundle:Atecnica:buscador" } 

atecnica_generoAgendaTecnico:
    pattern:  /{id}/generoAgendaTecnico
    defaults: { _controller: "AtBundle:Atecnica:generoAgendaTecnico" }

atecnica_asignarTecnicoAT:
    pattern:  /{at}/{tec}/asignarTecnicoAT
    defaults: { _controller: "AtBundle:Atecnica:asignarTecnicoAT" }
           
atecnica_cancelar:
    pattern:  /{id}/cancelar
    defaults: { _controller: "AtBundle:Atecnica:cancelar" }

atecnica_buscarAgendaTecnico:
    pattern:  /buscarAgendaTecnico
    defaults: { _controller: "AtBundle:Atecnica:buscarAgendaTecnico" }
    
   