atecnico:
    pattern:  /{atId}/index
    defaults: { _controller: "AtBundle:AtTecnico:index" }

atecnico_mapa:
    pattern:  /{atId}/mapa
    defaults: { _controller: "AtBundle:AtTecnico:mapa" }

atecnico_new:
    pattern:  /{atId}/{tecId}/new
    defaults: { _controller: "AtBundle:AtTecnico:new" }

atecnico_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "AtBundle:AtTecnico:eliminar" }

atecnico_show:
    path:     /{id}/show
    defaults: { _controller: "AtBundle:AtTecnico:show" }    