patrimonio_buscador:
    pattern:  /
    defaults: { _controller: "PatrimonioBundle:Patrimonio:buscador" }

patrimonio_index:
    pattern:  /
    defaults: { _controller: "PatrimonioBundle:Patrimonio:index" }

patrimonio_show:
    pattern:  /{id}/show
    defaults: { _controller: "PatrimonioBundle:Patrimonio:show" }

patrimonio_new:
    pattern:  /new
    defaults: { _controller: "PatrimonioBundle:Patrimonio:new" }

patrimonio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PatrimonioBundle:Patrimonio:edit" }

patrimonio_existe:
    pattern:  /existe/{id}
    defaults: { _controller: "PatrimonioBundle:Patrimonio:existe", id:null }
    
patrimonio_exportar:
    pattern:  /exportar
    defaults: { _controller: "PatrimonioBundle:Patrimonio:export" }
