security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPERPAT: [ROLE_USER]
        ROLE_TECNICO: [ROLE_OPERPAT]
        ROLE_JDS:   [ROLE_TECNICO]
        ROLE_ADMIN: [ROLE_JDS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/patrimonio/patrimonio/existe/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/patrimonio/, role: ROLE_OPERPAT }
        - { path: ^/backend/marca/, role: ROLE_OPERPAT }
        - { path: ^/backend/local/, role: ROLE_OPERPAT }
        - { path: ^/backend/patrimonioclasif/, role: ROLE_OPERPAT }
        - { path: ^/backend/, role: ROLE_ADMIN }
