local_listado:
    pattern:  /
    defaults: { _controller: BackendBundle:Local:index }

local_nuevo:
    pattern:  /new
    defaults: { _controller: BackendBundle:Local:new }

local_edit:
    pattern:  /edit/{id}
    defaults: { _controller: BackendBundle:Local:edit }

local_delete:
    pattern:  /delete/{id}
    defaults: { _controller: BackendBundle:Local:delete }

local_show:
    pattern:  /show/{id}
    defaults: { _controller: BackendBundle:Local:show }        

#backend_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: BackendBundle:Default:index }