repuesto:
    pattern:  /
    defaults: { _controller: "BackendBundle:Repuesto:index" }

repuesto_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Repuesto:show" }

repuesto_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Repuesto:new" }

repuesto_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Repuesto:create" }
    requirements: { _method: post }

repuesto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Repuesto:edit" }

repuesto_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Repuesto:update" }
    requirements: { _method: post|put }

repuesto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Repuesto:delete" }
    requirements: { _method: post|delete }

repuesto_eliminar:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Repuesto:eliminar" }