tecnico_listado:
    pattern:  /
    defaults: { _controller: "BackendBundle:Tecnico:index" }

tecnico_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Tecnico:show" }

tecnico_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Tecnico:new" }

tecnico_create:
    pattern:  /create
    defaults: { _controller: "BackendBundle:Tecnico:create" }
    requirements: { _method: post }

tecnico_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Tecnico:edit" }

tecnico_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendBundle:Tecnico:update" }
    requirements: { _method: post|put }

tecnico_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendBundle:Tecnico:delete" }
    requirements: { _method: post|delete }    
