
at_new:
    pattern:  /new
    defaults: { _controller: "FrontendBundle:At:new" }

at_show:
    pattern:  /{id}/show
    defaults: { _controller: "FrontendBundle:At:show" }

at_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FrontendBundle:At:edit" }  

at_ver_historico:
    pattern:  /{id}/ver_historico
    defaults: { _controller: "FrontendBundle:At:verHistorico" }

at_buscador:
    pattern:  /buscador
    defaults: { _controller: "FrontendBundle:At:buscador" } 

at_ver_ultimo_estadio:
    pattern:  /{id}/verUltimoEstadio
    defaults: { _controller: "FrontendBundle:At:verUltimoEstadio" }    
           
