backend_inicial:
    path:   /
    defaults: { _controller: BackendBundle:Default:index}

marca:
    resource: "@BackendBundle/Resources/config/routing/marca.yml"
    prefix:   /marca

local:
    resource: "@BackendBundle/Resources/config/routing/local.yml"
    prefix:   /local

patrimonioclasif:
    resource: "@BackendBundle/Resources/config/routing/patrimonioclasif.yml"
    prefix:   /patrimonioclasif

sectortipo:
    resource: "@BackendBundle/Resources/config/routing/sectortipo.yml"
    prefix:   /sectortipo

falla:
    resource: "@BackendBundle/Resources/config/routing/falla.yml"
    prefix:   /falla

sector:
    resource: "@BackendBundle/Resources/config/routing/sector.yml"
    prefix:   /sector

perfil:
    resource: "@BackendBundle/Resources/config/routing/perfil.yml"
    prefix:   /perfil  

tecnico:
    resource: "@BackendBundle/Resources/config/routing/tecnico.yml"
    prefix:   /tecnico  

prioridad:
    resource: "@BackendBundle/Resources/config/routing/prioridad.yml"
    prefix:   /prioridad

estadioclasif:
    resource: "@BackendBundle/Resources/config/routing/estadioclasif.yml"
    prefix:   /estadioclasif  

estadio:
    resource: "@BackendBundle/Resources/config/routing/estadio.yml"
    prefix:   /estadio               

rol:
    resource: "@BackendBundle/Resources/config/routing/rol.yml"
    prefix:   /rol

repuesto:
    resource: "@BackendBundle/Resources/config/routing/repuesto.yml"
    prefix:   /repuesto

proveedor:
    resource: "@BackendBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

serviciotercero:
    resource: "@BackendBundle/Resources/config/routing/serviciotercero.yml"
    prefix:   /serviciotercero