atecnica_inicial:
    path:   /
    defaults: { _controller: AtBundle:Default:index}

atecnica:
  resource: "@AtBundle/Resources/config/routing/Atecnica.yml"
  prefix:   /atecnica

at_nota:
  resource: "@AtBundle/Resources/config/routing/AtNota.yml"
  prefix:   /at_nota   

at_falla:
  resource: "@AtBundle/Resources/config/routing/AtFalla.yml"
  prefix:   /at_falla  

at_tecnico:
  resource: "@AtBundle/Resources/config/routing/AtTecnico.yml"
  prefix:   /at_tecnico 
  
at_servicio:
  resource: "@AtBundle/Resources/config/routing/AtServicio.yml"
  prefix:   /at_servicio  

at_repuesto:
  resource: "@AtBundle/Resources/config/routing/AtRepuesto.yml"
  prefix:   /at_repuesto  

at_falla:
  resource: "@AtBundle/Resources/config/routing/AtFalla.yml"
  prefix:   /at_falla   

at_historico:
  resource: "@AtBundle/Resources/config/routing/AtHistorico.yml"
  prefix:   /at_historico    