atecnica_inicial:
    path:   /
    defaults: { _controller: AtBundle:Default:index}

atecnica:
  resource: "@AtBundle/Resources/config/routing/Atecnica.yml"
  prefix:   /atecnica

at_nota:
  resource: "@AtBundle/Resources/config/routing/AtNota.yml"
  prefix:   /at_nota   

at_falla:
  resource: "@AtBundle/Resources/config/routing/AtFalla.yml"
  prefix:   /at_falla          
